# Generated by Django 2.2 on 2019-04-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectiontaskmapper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
