# Generated by Django 2.2 on 2019-04-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectiontaskmapper', '0002_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
